# Generated by Django 6.0.1 on 2026-01-25 01:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_prescription_scheduled_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='scheduled_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
