# Generated by Django 6.0.1 on 2026-02-22 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0004_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='last_seen',
        ),
    ]
