# Generated by Django 6.0.1 on 2026-02-22 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0005_remove_device_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
