# Generated by Django 6.0.1 on 2026-02-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0006_prescription_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='last_notified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
