# Generated by Django 6.0.2 on 2026-03-06 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0007_prescription_last_notified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionLogging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('REMINDER_SENT', 'Reminder Sent'), ('TAKEN', 'Taken'), ('MISSED', 'Missed')], max_length=20)),
                ('scheduled_time', models.DateTimeField()),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='prescriptions.prescription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
