# Generated by Django 6.0.2 on 2026-03-21 19:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0009_errorlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='ready',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='scheduled_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
