# Generated by Django 6.0.2 on 2026-04-10 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0013_push_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpreference',
            name='sms_enabled',
        ),
    ]
