# Generated by Django 6.0.2 on 2026-04-11 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0018_userprofile_rfid_uid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionlogging',
            name='event_type',
            field=models.CharField(choices=[('REMINDER_SENT', 'Reminder Sent'), ('TAKEN', 'Taken'), ('MISSED', 'Missed'), ('REFILL', 'Refill')], max_length=20),
        ),
        migrations.CreateModel(
            name='RFIDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(help_text='Physical RFID card UID (e.g. 87447d33)', max_length=64, unique=True)),
                ('assigned_to', models.OneToOneField(blank=True, help_text='User this card is assigned to (blank = available)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfid_card', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
