# Generated by Django 6.0.2 on 2026-04-14 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0012_failedloginlog'),
        ('prescriptions', '0019_rfid_card_pool'),
    ]

    operations = [
    ]
