# Generated by Django 6.0.2 on 2026-04-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0021_revert_prescription_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='add_stock',
            field=models.PositiveIntegerField(default=0, help_text='Pills to add on top of the next MCU stock report'),
        ),
    ]
