# Generated by Django 6.0.2 on 2026-04-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0022_add_stock_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionlogging',
            name='event_type',
            field=models.CharField(choices=[('REMINDER_SENT', 'Reminder Sent'), ('TAKEN', 'Taken'), ('MISSED', 'Missed'), ('REFILL', 'Refill'), ('DISPENSE_SENT', 'Dispense Sent to MCU')], max_length=20),
        ),
    ]
