# Generated by Django 6.0.2 on 2026-04-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0023_alter_prescriptionlogging_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionlogging',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Pills involved in this event', null=True),
        ),
    ]
