# Generated by Django 6.0.2 on 2026-04-18 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0024_add_quantity_to_logging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='add_stock',
            field=models.PositiveIntegerField(default=0, help_text='Pills to add on top of the next MCU stock report (capped so total does not exceed 30)', validators=[django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='stock_count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(30)]),
        ),
    ]
