# Generated by Django 6.0.2 on 2026-04-18 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0025_alter_prescription_add_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='frequency',
        ),
        migrations.AddField(
            model_name='prescription',
            name='doses_per_day',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of doses per day'),
        ),
        migrations.CreateModel(
            name='DoseTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_day', models.TimeField()),
                ('label', models.CharField(blank=True, default='', help_text='e.g. Morning, Afternoon, Evening', max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose_times', to='prescriptions.prescription')),
            ],
            options={
                'ordering': ['order', 'time_of_day'],
            },
        ),
    ]
