# Generated by Django 6.0.2 on 2026-04-18 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0026_frequency_to_doses_per_day_and_dosetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dosetime',
            options={'ordering': ['time_of_day']},
        ),
        migrations.RemoveField(
            model_name='dosetime',
            name='order',
        ),
    ]
