# Generated by Django 6.0.2 on 2026-04-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0027_remove_dosetime_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='window_minutes',
            field=models.PositiveSmallIntegerField(default=30, help_text='Minutes after dose time before the window expires and dose is marked missed'),
        ),
        migrations.AlterField(
            model_name='prescriptionlogging',
            name='event_type',
            field=models.CharField(choices=[('REMINDER_SENT', 'Reminder Sent'), ('WARNING', 'Window Warning'), ('TAKEN', 'Taken'), ('MISSED', 'Missed'), ('REFILL', 'Refill'), ('DISPENSE_SENT', 'Dispense Sent to MCU')], max_length=20),
        ),
    ]
