# Generated by Django 6.0.2 on 2026-04-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0028_add_window_minutes_and_warning_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='window_before_minutes',
            field=models.PositiveSmallIntegerField(default=15, help_text='Minutes before dose time that the window opens (patient can take medication early)'),
        ),
    ]
