# Generated by Django 6.0.2 on 2026-04-21 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0029_add_window_before_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='window_before_minutes',
            field=models.PositiveSmallIntegerField(default=15, help_text='Minutes before dose time the window opens (minimum 5)', validators=[django.core.validators.MinValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='window_minutes',
            field=models.PositiveSmallIntegerField(default=30, help_text='Minutes after dose time before window expires (minimum 5)', validators=[django.core.validators.MinValueValidator(5)]),
        ),
    ]
